models.py
from peewee import *

db = SqliteDatabase('moradoresDB.db')

class BaseModel(Model):
    class Meta:
        database = db

class User(BaseModel):
    nome = CharField()
    cpf = CharField(unique=True)
    bloco = IntegerField()
    apartamento = IntegerField()
    tipo = CharField()

class Vote(BaseModel):
    user = ForeignKeyField(User, backref='votes')
    voted_for = CharField()
    apartamento = IntegerField()
def initialize_db():
    db.connect()
    db.create_tables([User, Vote], safe=True)
    db.close() 

app.py
from flask import Flask ,render_template

#Rotas
from routes.eleicoes_route import eleicao_bp
from routes.registro_route import registro_bp
from routes.resultados import resultado_bp

#Database
from models import initialize_db

#inicializa o Flask
app = Flask(__name__)
app.config['SECRET_KEY'] = 'sua_chave_secreta'

#blueprints
app.register_blueprint(eleicao_bp, url_prefix='/eleicao')
app.register_blueprint(registro_bp, url_prefix='/cadastro')
app.register_blueprint(resultado_bp, url_prfix='/resultado')

#rota da pagina inicial
@app.route('/')
def home():
    return render_template('index.html')

initialize_db()

if __name__ == "__main__":
    app.run(debug=True)

routes/eleicoes_route.py
from flask import render_template, redirect, url_for, Blueprint, request
from models import User, Vote

eleicao_bp = Blueprint('eleicao', __name__)

@eleicao_bp.route('/votar', methods=['GET', 'POST'])
def votar():
    if request.method == 'POST':
        if not request.form:
            return render_template('mensagem.html', exibir_modal_erro=True)


        cpf = request.form['cpf']
        candidato_id = request.form['candidato_id']

        if Vote.select().where(Vote.user == cpf).exists():
            return render_template('mensagem.html', mensagem='Você já votou.')

        usuario = User.get(User.cpf == cpf)
        if Vote.select().where(Vote.apartamento == usuario.apartamento).exists():
            return render_template('mensagem.html', mensagem='Já foi registrado um voto neste apartamento.')

        Vote.create(user=cpf, voted_for=candidato_id, apartamento=usuario.apartamento)
        return redirect(url_for('eleicao.votar'))

    candidatos = User.select().where(User.tipo == 'candidato')
    return render_template('votacao.html', candidatos=candidatos)

routes/registro_route.py
from flask import render_template, request, redirect, url_for, Blueprint
from models import User

registro_bp = Blueprint('cadastro', __name__)

@registro_bp.route('/registrar_usuario', methods=['GET', 'POST'])
def registrar_usuario():
    if request.method == 'POST':

        if not request.form:
            return render_template('mensagem.html', exibir_modal_erro=True)


        nome = request.form['nome']
        cpf = request.form['cpf']
        bloco = request.form['bloco']
        apartamento = request.form['apartamento']
        tipo = request.form['tipo']
        

        # Verificar se o usuário já está registrado
        if User.select().where(User.cpf == cpf).exists():
            return render_template('mensagem.html', mensagem='Usuário já registrado.')

        # Criar um novo usuário no banco de dados
        User.create(nome=nome, cpf=cpf, bloco=bloco, apartamento=apartamento, tipo=tipo)
    
        return redirect(url_for('home'))

    return render_template('cadastro.html')

routes/resultados.py
from flask import render_template, Blueprint
from models import Vote, User
from peewee import fn
import plotly.graph_objs as go

resultado_bp = Blueprint('resultado', __name__)

@resultado_bp.route('/resultado')
def resultados():
    print("Acessou a rota /resultados")
    # Consultar o banco de dados para contar os votos de cada candidato
    resultados = Vote.select(Vote.voted_for, fn.COUNT(Vote.id).alias('total_votos')).group_by(Vote.voted_for)

    # Extrair os dados para plotar o gráfico de barras
    candidatos = []
    votos = []
    for resultado in resultados:
        candidato = User.get(User.id == resultado.voted_for)
        candidatos.append(candidato.nome)
        votos.append(resultado.total_votos)
        print(f"Candidato: {candidato.nome}, Votos: {resultado.total_votos}")

    # Criar o gráfico de barras
    grafico = go.Figure(data=[go.Bar(x=candidatos, y=votos)])

    # Converter o gráfico em HTML
    grafico_html = grafico.to_html(full_html=False)
    print(f"HTML do gráfico: {grafico_html}")

    return render_template('resultados.html', grafico_html=grafico_html)

templates/cadastro.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="p-3 mb-2 bg-dark text-white">
    <div class="container">
        <h1 class="mt-5">Cadastro</h1>

        <form method="POST">
            <div class="mb-3">
                <label for="nome" class="form-label">Nome</label>
                <input type="text" class="form-control" id="nome" name="nome">
            </div>
            <div class="mb-3">
                <label for="cpf" class="form-label">CPF</label>
                <input type="text" class="form-control" id="cpf" name="cpf">
            </div>
            <div class="mb-3">
                <label for="apartamento" class="form-label">Apartamento</label>
                <input type="text" class="form-control" id="apartamento" name="apartamento">
            </div>
            <div class="mb-3">
                <label for="bloco" class="form-label">Bloco</label>
                <input type="text" class="form-control" id="bloco" name="bloco">
            </div>
            <div class="mb-3">
                <label for="tipo" class="form-label">Tipo de Cadastro</label>
                <select class="form-select" id="tipo" name="tipo">
                    <option value="nada"></option>
                    <option value="candidato">Candidato</option>
                    <option value="morador">Morador</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vote Predio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="p-3 mb-2 bg-dark text-white" >
    <div class="container ">
        <div class="centralized">
            <h1 class="text-center mt-5">E-leição</h1>
            <h6 class="text-center mt-5">Página inicial</h6>
        </div>
        <div class="mt-5 text-center">
            <a href="{{ url_for('cadastro.registrar_usuario') }}" class="btn btn-primary mt-3">Cadastrar Morador</a>
            <a href="{{ url_for('eleicao.votar') }}" class="btn btn-success mt-3">Votar</a>
            <a href="{{ url_for('resultado.resultados') }}" class="btn btn-secondary mt-3">Ver Resultados</a>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/mensagem.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mensagem</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <div class="container">
        <div class="alert alert-danger mt-5" role="alert">
            {{ mensagem }}
        </div>
        <a href="{{ url_for('home') }}" class="btn btn-secondary mt-3">voltar para a tela inicial</a>
    </div>

    <!-- Modal de Erro -->
    <div class="modal fade" id="modalErro" tabindex="-1" aria-labelledby="modalErroLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalErroLabel">Erro</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Nenhum dado foi inserido.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        $(document).ready(function() {
          {% if exibir_modal_erro %}
            $('#modalErro').modal('show');
          {% endif %}
        });
      </script>
</body>

</html>

templates/resultados.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resultados da Votação</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body class="p-3 mb-2 bg-dark text-white">
    <div class="container">
        <h1 class="mt-5 mb-4">Resultados da Votação</h1>

        <div id="grafico" class="mt-3"></div>

    </div>

    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script>
        console.log('JavaScript está sendo executado!');
        var grafico_div = document.getElementById('grafico');
        grafico_div.innerHTML = '{{ grafico_html|safe }}';
    </script>
    <a href="{{ url_for('home') }}" class="btn btn-secondary mt-3">voltar para a tela inicial</a>
    
</body>
</html>

templates/votacao.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Votação</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="p-3 mb-2 bg-dark text-white">
    <div class="container">
        <h1 class="mt-5">Votação</h1>
        {% if error %}
            <div class="alert alert-danger mt-3" role="alert">{{ error }}</div>
        {% endif %}
        <form method="POST" action="{{url_for('eleicao.votar')}}">
            <div class="mb-3">
                <label for="cpf" class="form-label">CPF</label>
                <input type="text" class="form-control" id="cpf" name="cpf">
            </div>
            <div class="mb-3">
                <label for="candidato" class="form-label">Escolha</label>
                <select class="form-select" id="candidato" name="candidato_id">
                    {% for candidato in candidatos %}
                        <option value="{{ candidato.id }}">{{ candidato.nome }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Votar</button>
        </form>
        <a href="{{ url_for('home') }}" class="btn btn-secondary mt-3">voltar para a tela inicial</a>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>